// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TitleContainer;
lv_obj_t * ui_titleLabel;
lv_obj_t * ui_weightPanel;
lv_obj_t * ui_weightLabel;
lv_obj_t * ui_weightLabelDot;
lv_obj_t * ui_weightLabelSmall;
lv_obj_t * ui_KgLabel;
lv_obj_t * ui_M1Panel;
lv_obj_t * ui_weightM1Label;
lv_obj_t * ui_weightLabelDot11;
lv_obj_t * ui_M1Label;
lv_obj_t * ui_M2Panel;
lv_obj_t * ui_confirmContainer;
lv_obj_t * ui_confirmPanel;
lv_obj_t * ui_confirmTextLabel;
void ui_event_OKButton(lv_event_t * e);
lv_obj_t * ui_OKButton;
lv_obj_t * ui_OKLabel;
lv_obj_t * ui_CANCELButton;
lv_obj_t * ui_CANCELLabel;


// SCREEN: ui_logScreen
void ui_logScreen_screen_init(void);
lv_obj_t * ui_logScreen;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_TextArea1;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_OKButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_confirmContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_logScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
