// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TitleContainer;
lv_obj_t * ui_titleLabel;
void ui_event_weightPanel(lv_event_t * e);
lv_obj_t * ui_weightPanel;
lv_obj_t * ui_weightLabel;
lv_obj_t * ui_weightLabelDot;
lv_obj_t * ui_weightLabelSmall;
lv_obj_t * ui_KgLabel;
void ui_event_deltaPanel(lv_event_t * e);
lv_obj_t * ui_deltaPanel;
lv_obj_t * ui_weightDeltaLabel;
lv_obj_t * ui_weightLabelDot10;
lv_obj_t * ui_weightDeltaLabelSmall;
lv_obj_t * ui_Label7;
void ui_event_M1Panel(lv_event_t * e);
lv_obj_t * ui_M1Panel;
lv_obj_t * ui_weightM1Label;
lv_obj_t * ui_weightLabelDot11;
lv_obj_t * ui_weightM1LabelSmall;
lv_obj_t * ui_M1Label;
void ui_event_M2Panel(lv_event_t * e);
lv_obj_t * ui_M2Panel;
lv_obj_t * ui_M1Label1;
void ui_event_M3Panel(lv_event_t * e);
lv_obj_t * ui_M3Panel;
lv_obj_t * ui_weightM3Label;
lv_obj_t * ui_weightLabelDot13;
lv_obj_t * ui_weightM3LabelSmall;
lv_obj_t * ui_M1Label2;
void ui_event_M4Panel(lv_event_t * e);
lv_obj_t * ui_M4Panel;
lv_obj_t * ui_weightM4Label;
lv_obj_t * ui_weightLabelDot14;
lv_obj_t * ui_weightM4LabelSmall;
lv_obj_t * ui_M1Label3;
lv_obj_t * ui_confirmContainer;
lv_obj_t * ui_confirmPanel;
lv_obj_t * ui_confirmTextLabel;
void ui_event_OKButton(lv_event_t * e);
lv_obj_t * ui_OKButton;
lv_obj_t * ui_OKLabel;
void ui_event_CANCELButton(lv_event_t * e);
lv_obj_t * ui_CANCELButton;
lv_obj_t * ui_CANCELLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_weightPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmResetWeightWindow(e);
    }
}
void ui_event_deltaPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmDeltaWindow(e);
    }
}
void ui_event_M1Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmStoreM1Window(e);
    }
}
void ui_event_M2Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmStoreM2Window(e);
    }
}
void ui_event_M3Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmStoreM3Window(e);
    }
}
void ui_event_M4Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ShowConfirmStoreM4Window(e);
    }
}
void ui_event_OKButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_confirmContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        uicb_ConfirmButton(e);
    }
}
void ui_event_CANCELButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_confirmContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
