// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_TitleContainer;
extern lv_obj_t * ui_titleLabel;
void ui_event_weightPanel(lv_event_t * e);
extern lv_obj_t * ui_weightPanel;
extern lv_obj_t * ui_weightLabel;
extern lv_obj_t * ui_weightLabelDot;
extern lv_obj_t * ui_weightLabelSmall;
extern lv_obj_t * ui_KgLabel;
void ui_event_deltaPanel(lv_event_t * e);
extern lv_obj_t * ui_deltaPanel;
extern lv_obj_t * ui_weightDeltaLabel;
extern lv_obj_t * ui_weightLabelDot10;
extern lv_obj_t * ui_weightDeltaLabelSmall;
extern lv_obj_t * ui_Label7;
void ui_event_M1Panel(lv_event_t * e);
extern lv_obj_t * ui_M1Panel;
extern lv_obj_t * ui_weightM1Label;
extern lv_obj_t * ui_weightLabelDot11;
extern lv_obj_t * ui_weightM1LabelSmall;
extern lv_obj_t * ui_M1Label;
void ui_event_M2Panel(lv_event_t * e);
extern lv_obj_t * ui_M2Panel;
extern lv_obj_t * ui_M1Label1;
void ui_event_M3Panel(lv_event_t * e);
extern lv_obj_t * ui_M3Panel;
extern lv_obj_t * ui_weightM3Label;
extern lv_obj_t * ui_weightLabelDot13;
extern lv_obj_t * ui_weightM3LabelSmall;
extern lv_obj_t * ui_M1Label2;
void ui_event_M4Panel(lv_event_t * e);
extern lv_obj_t * ui_M4Panel;
extern lv_obj_t * ui_weightM4Label;
extern lv_obj_t * ui_weightLabelDot14;
extern lv_obj_t * ui_weightM4LabelSmall;
extern lv_obj_t * ui_M1Label3;
extern lv_obj_t * ui_confirmContainer;
extern lv_obj_t * ui_confirmPanel;
extern lv_obj_t * ui_confirmTextLabel;
void ui_event_OKButton(lv_event_t * e);
extern lv_obj_t * ui_OKButton;
extern lv_obj_t * ui_OKLabel;
void ui_event_CANCELButton(lv_event_t * e);
extern lv_obj_t * ui_CANCELButton;
extern lv_obj_t * ui_CANCELLabel;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_weight100Font);
LV_FONT_DECLARE(ui_font_weight12Font);
LV_FONT_DECLARE(ui_font_weight200Font);
LV_FONT_DECLARE(ui_font_weight25Font);
LV_FONT_DECLARE(ui_font_weight50Font);
LV_FONT_DECLARE(ui_font_weightLargeFont);
LV_FONT_DECLARE(ui_font_weightSmallFont);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
