// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void uicb_ShowConfirmResetWeightWindow(lv_event_t * e);
void uicb_ShowConfirmDeltaWindow(lv_event_t * e);
void uicb_ShowConfirmStoreM1Window(lv_event_t * e);
void uicb_ShowConfirmStoreM2Window(lv_event_t * e);
void uicb_ShowConfirmStoreM3Window(lv_event_t * e);
void uicb_ShowConfirmStoreM4Window(lv_event_t * e);
void uicb_ConfirmButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
