// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ui_test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_TitleContainer;
lv_obj_t * ui_titleLabel;
lv_obj_t * ui_tempPanel;
lv_obj_t * ui_tempLabel;
lv_obj_t * ui_tempLabelDot;
lv_obj_t * ui_tempLabelSmall;
lv_obj_t * ui_unitLabel;
lv_obj_t * ui_setpointPanel;
lv_obj_t * ui_setPointLabel;
lv_obj_t * ui_weightLabelDot11;
lv_obj_t * ui_setPointSmallLabel;
lv_obj_t * ui_SETLabel;
lv_obj_t * ui_coolHeatPanel;
lv_obj_t * ui_coolHeatLabel;
lv_obj_t * ui_coolHeatBar;
lv_obj_t * ui_infoPanel;
lv_obj_t * ui_temperatureChart;
lv_obj_t * ui_statusContainer;
lv_obj_t * ui_timeContainer;
lv_obj_t * ui_timeLabel;
lv_obj_t * ui_backendContainer;
lv_obj_t * ui_backendBar;
lv_obj_t * ui_networkContainer;
lv_obj_t * ui_rssiContainer;
lv_obj_t * ui_rssiImage;
void ui_event_setPanel(lv_event_t * e);
lv_obj_t * ui_setPanel;
lv_obj_t * ui_testLabel;
lv_obj_t * ui_setLabel;
void ui_event_modePanel(lv_event_t * e);
lv_obj_t * ui_modePanel;
lv_obj_t * ui_modeLabel;
lv_obj_t * ui_confirmContainer;
lv_obj_t * ui_confirmPanel;
lv_obj_t * ui_confirmTextLabel;
void ui_event_OKButton(lv_event_t * e);
lv_obj_t * ui_OKButton;
lv_obj_t * ui_OKLabel;
lv_obj_t * ui_CANCELButton;
lv_obj_t * ui_CANCELLabel;
lv_obj_t * ui_Switch1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1asset_[1] = {&ui_img_icons_1asset_33_png};
const lv_img_dsc_t * ui_imgset_1985688160[1] = {&ui_img_1173369594};
const lv_img_dsc_t * ui_imgset_2asset_[1] = {&ui_img_icons_2asset_34_png};
const lv_img_dsc_t * ui_imgset_1408649500[1] = {&ui_img_517907122};
const lv_img_dsc_t * ui_imgset_3asset_[1] = {&ui_img_icons_3asset_35_png};
const lv_img_dsc_t * ui_imgset_273650268[1] = {&ui_img_556913678};
const lv_img_dsc_t * ui_imgset_4asset_[1] = {&ui_img_icons_4asset_36_png};
const lv_img_dsc_t * ui_imgset_312858336[1] = {&ui_img_1949788358};
const lv_img_dsc_t * ui_imgset_5asset_[1] = {&ui_img_icons_5asset_37_png};
const lv_img_dsc_t * ui_imgset_1447857568[1] = {&ui_img_1745259782};
const lv_img_dsc_t * ui_imgset_6asset_[1] = {&ui_img_icons_6asset_38_png};
const lv_img_dsc_t * ui_imgset_1372527238[1] = {&ui_img_1659350234};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_setPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsScreen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_settingsScreen2_screen_init);
    }
}
void ui_event_modePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_modeScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_modeScreen_screen_init);
    }
}
void ui_event_OKButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_confirmContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
