; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = no_display
;default_envs = lcd_12864
;default_envs = lcd_i2c_16x2
default_envs =  cyd_320x240

[env]
board       = wemos_d1_mini32
platform    = espressif32
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed    = 921600
lib_ldf_mode    = chain+
check_tool       = clangtidy
monitor_filters = 
   direct
   esp32_exception_decoder
lib_deps = 
   milesburton/DallasTemperature@^3.11.0
   marian-craciunescu/ESP32Ping@^1.7
   bblanchon/ArduinoJson@^6.20.1
   khoih-prog/ESP_DoubleResetDetector@>=1.3.2
   ottowinter/ESPAsyncWebServer-esphome@^3.1.0
   https://github.com/guestisp/ESP32AsyncDNSServer ; fork uses native AsyncUDP

[env:no_display]
build_flags =
   -DCFG_DISPLAY_NONE=1

[env:lcd_i2c_16x2]
lib_deps = 
  ${env.lib_deps}
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags =
  -DCFG_DISPLAY_LCD_I2C_16X2=1

[env:lcd_12864]
lib_deps = 
  ${env.lib_deps}
  olikraus/U8g2@^2.35.7
build_flags =
  -DCFG_DISPLAY_LCD_12864=1

[env:cyd_320x240]
;board = esp32-2432S028Rv2
lib_deps = 
  ${env.lib_deps}
  git+https://github.com/rzeldent/esp32-smartdisplay
build_flags =
  -Ofast
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  -DLV_CONF_PATH=${PROJECT_INCLUDE_DIR}/lv_conf.h   
  -DCFG_DISPLAY_CYD_320x240=1


