[wokwi]
version = 1
elf = ".pio/build/cyd_320x240/firmware.elf"
firmware = ".pio/build/cyd_320x240/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
#[[net.forward]]
#from = "localhost:8180"
#to = "target:80"
