// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ui_480x320_HB

#include "ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x506679), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_TitleContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_TitleContainer);
    lv_obj_set_width(ui_TitleContainer, 480);
    lv_obj_set_height(ui_TitleContainer, 18);
    lv_obj_set_x(ui_TitleContainer, 0);
    lv_obj_set_y(ui_TitleContainer, -151);
    lv_obj_set_align(ui_TitleContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitleContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TitleContainer, lv_color_hex(0x4646BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleLabel = lv_label_create(ui_TitleContainer);
    lv_obj_set_align(ui_titleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleLabel, "BOOKES BRICK HB");
    lv_obj_set_style_text_color(ui_titleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setpointPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_setpointPanel, 115);
    lv_obj_set_height(ui_setpointPanel, 48);
    lv_obj_set_x(ui_setpointPanel, -178);
    lv_obj_set_y(ui_setpointPanel, -11);
    lv_obj_set_align(ui_setpointPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_setpointPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_setpointPanel, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setpointPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setpointPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setpointPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setpointPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_setpointPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_setPointLabel = lv_label_create(ui_setpointPanel);
    lv_obj_set_width(ui_setPointLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setPointLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setPointLabel, -19);
    lv_obj_set_y(ui_setPointLabel, 11);
    lv_obj_set_align(ui_setPointLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_setPointLabel, "--");
    lv_obj_set_style_text_color(ui_setPointLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setPointLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setPointLabel, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLabelDot11 = lv_label_create(ui_setpointPanel);
    lv_obj_set_width(ui_weightLabelDot11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabelDot11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabelDot11, 17);
    lv_obj_set_y(ui_weightLabelDot11, 8);
    lv_obj_set_align(ui_weightLabelDot11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weightLabelDot11, ".");
    lv_obj_set_style_text_color(ui_weightLabelDot11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLabelDot11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLabelDot11, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setPointSmallLabel = lv_label_create(ui_setpointPanel);
    lv_obj_set_width(ui_setPointSmallLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setPointSmallLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setPointSmallLabel, 4);
    lv_obj_set_y(ui_setPointSmallLabel, 11);
    lv_obj_set_align(ui_setPointSmallLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_setPointSmallLabel, "-");
    lv_obj_set_style_text_color(ui_setPointSmallLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setPointSmallLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setPointSmallLabel, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SETLabel = lv_label_create(ui_setpointPanel);
    lv_obj_set_width(ui_SETLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SETLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SETLabel, 41);
    lv_obj_set_y(ui_SETLabel, -11);
    lv_obj_set_align(ui_SETLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SETLabel, "SET");
    lv_obj_set_style_text_color(ui_SETLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SETLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolHeatPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_coolHeatPanel, 115);
    lv_obj_set_height(ui_coolHeatPanel, 48);
    lv_obj_set_x(ui_coolHeatPanel, -60);
    lv_obj_set_y(ui_coolHeatPanel, -11);
    lv_obj_set_align(ui_coolHeatPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_coolHeatPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_coolHeatPanel, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolHeatPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_coolHeatPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_coolHeatPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_coolHeatPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_coolHeatPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_border_color(ui_coolHeatPanel, lv_color_hex(0xB7B7B7), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_coolHeatPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_offLabel = lv_label_create(ui_coolHeatPanel);
    lv_obj_set_width(ui_offLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offLabel, 0);
    lv_obj_set_y(ui_offLabel, -11);
    lv_obj_set_align(ui_offLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offLabel, "OFF");
    lv_obj_set_style_text_color(ui_offLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_offLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolLabel = lv_label_create(ui_coolHeatPanel);
    lv_obj_set_width(ui_coolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_coolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_coolLabel, 0);
    lv_obj_set_y(ui_coolLabel, -10);
    lv_obj_set_align(ui_coolLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_coolLabel, "COOL");
    lv_obj_add_flag(ui_coolLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_coolLabel, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_coolLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heatLabel = lv_label_create(ui_coolHeatPanel);
    lv_obj_set_width(ui_heatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heatLabel, 0);
    lv_obj_set_y(ui_heatLabel, -10);
    lv_obj_set_align(ui_heatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heatLabel, "HEAT");
    lv_obj_add_flag(ui_heatLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_heatLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coolBar = lv_bar_create(ui_coolHeatPanel);
    lv_bar_set_value(ui_coolBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_coolBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_coolBar, 73);
    lv_obj_set_height(ui_coolBar, 14);
    lv_obj_set_x(ui_coolBar, 0);
    lv_obj_set_y(ui_coolBar, 9);
    lv_obj_set_align(ui_coolBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coolBar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_coolBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_coolBar, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_coolBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_heatBar = lv_bar_create(ui_coolHeatPanel);
    lv_bar_set_value(ui_heatBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_heatBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_heatBar, 73);
    lv_obj_set_height(ui_heatBar, 14);
    lv_obj_set_x(ui_heatBar, 0);
    lv_obj_set_y(ui_heatBar, 9);
    lv_obj_set_align(ui_heatBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heatBar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_heatBar, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_heatBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heatBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_heatBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heatBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_tempGraphPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_tempGraphPanel, 471);
    lv_obj_set_height(ui_tempGraphPanel, 113);
    lv_obj_set_x(ui_tempGraphPanel, 0);
    lv_obj_set_y(ui_tempGraphPanel, 73);
    lv_obj_set_align(ui_tempGraphPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempGraphPanel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempGraphPanel, lv_color_hex(0xEEEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempGraphPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempGraphPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempGraphPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempGraphPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tempGraphPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_border_color(ui_tempGraphPanel, lv_color_hex(0xB7B7B7), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempGraphPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_temperatureChart = lv_chart_create(ui_tempGraphPanel);
    lv_obj_set_width(ui_temperatureChart, 385);
    lv_obj_set_height(ui_temperatureChart, 100);
    lv_obj_set_align(ui_temperatureChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temperatureChart,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);    /// Flags
    lv_chart_set_type(ui_temperatureChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_temperatureChart, 125);
    lv_chart_set_range(ui_temperatureChart, LV_CHART_AXIS_PRIMARY_Y, 5, 35);
    lv_chart_set_range(ui_temperatureChart, LV_CHART_AXIS_SECONDARY_Y, 1000, 1150);
    lv_chart_set_axis_tick(ui_temperatureChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 1, 10, false, 50);
    lv_chart_set_axis_tick(ui_temperatureChart, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 3, 1, true, 50);
    lv_chart_set_axis_tick(ui_temperatureChart, LV_CHART_AXIS_SECONDARY_Y, 5, 5, 3, 1, true, 50);



    ui_statusContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_statusContainer);
    lv_obj_set_width(ui_statusContainer, 480);
    lv_obj_set_height(ui_statusContainer, 26);
    lv_obj_set_x(ui_statusContainer, 0);
    lv_obj_set_y(ui_statusContainer, 147);
    lv_obj_set_align(ui_statusContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statusContainer, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_networkContainer = lv_obj_create(ui_statusContainer);
    lv_obj_remove_style_all(ui_networkContainer);
    lv_obj_set_width(ui_networkContainer, 45);
    lv_obj_set_height(ui_networkContainer, 22);
    lv_obj_set_x(ui_networkContainer, -215);
    lv_obj_set_y(ui_networkContainer, 0);
    lv_obj_set_align(ui_networkContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_networkContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_networkContainer, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_networkContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiContainer = lv_obj_create(ui_networkContainer);
    lv_obj_remove_style_all(ui_rssiContainer);
    lv_obj_set_width(ui_rssiContainer, 30);
    lv_obj_set_height(ui_rssiContainer, 22);
    lv_obj_set_x(ui_rssiContainer, -8);
    lv_obj_set_y(ui_rssiContainer, -1);
    lv_obj_set_align(ui_rssiContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rssiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rssiBar0Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiBar0Panel, 5);
    lv_obj_set_height(ui_rssiBar0Panel, 4);
    lv_obj_set_x(ui_rssiBar0Panel, -8);
    lv_obj_set_y(ui_rssiBar0Panel, 5);
    lv_obj_set_align(ui_rssiBar0Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rssiBar0Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_rssiBar0Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiBar0Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiBar0Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiBar0Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiBar1Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiBar1Panel, 5);
    lv_obj_set_height(ui_rssiBar1Panel, 8);
    lv_obj_set_x(ui_rssiBar1Panel, -2);
    lv_obj_set_y(ui_rssiBar1Panel, 3);
    lv_obj_set_align(ui_rssiBar1Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rssiBar1Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_rssiBar1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiBar1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rssiBar1Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rssiBar1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiBar1Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiBar1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiBar2Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiBar2Panel, 5);
    lv_obj_set_height(ui_rssiBar2Panel, 12);
    lv_obj_set_x(ui_rssiBar2Panel, 4);
    lv_obj_set_y(ui_rssiBar2Panel, 1);
    lv_obj_set_align(ui_rssiBar2Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rssiBar2Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_rssiBar2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiBar2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rssiBar2Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rssiBar2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiBar2Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiBar2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiBar3Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiBar3Panel, 5);
    lv_obj_set_height(ui_rssiBar3Panel, 15);
    lv_obj_set_x(ui_rssiBar3Panel, 10);
    lv_obj_set_y(ui_rssiBar3Panel, -1);
    lv_obj_set_align(ui_rssiBar3Panel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rssiBar3Panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_rssiBar3Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiBar3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rssiBar3Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rssiBar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiBar3Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiBar3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiLine0Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiLine0Panel, 5);
    lv_obj_set_height(ui_rssiLine0Panel, 2);
    lv_obj_set_x(ui_rssiLine0Panel, -8);
    lv_obj_set_y(ui_rssiLine0Panel, 9);
    lv_obj_set_align(ui_rssiLine0Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rssiLine0Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiLine0Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiLine0Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiLine0Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiLine1Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiLine1Panel, 5);
    lv_obj_set_height(ui_rssiLine1Panel, 2);
    lv_obj_set_x(ui_rssiLine1Panel, -2);
    lv_obj_set_y(ui_rssiLine1Panel, 9);
    lv_obj_set_align(ui_rssiLine1Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rssiLine1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiLine1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiLine1Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiLine1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiLine2Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiLine2Panel, 5);
    lv_obj_set_height(ui_rssiLine2Panel, 2);
    lv_obj_set_x(ui_rssiLine2Panel, 4);
    lv_obj_set_y(ui_rssiLine2Panel, 9);
    lv_obj_set_align(ui_rssiLine2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rssiLine2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiLine2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiLine2Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiLine2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiLine3Panel = lv_obj_create(ui_rssiContainer);
    lv_obj_set_width(ui_rssiLine3Panel, 5);
    lv_obj_set_height(ui_rssiLine3Panel, 2);
    lv_obj_set_x(ui_rssiLine3Panel, 10);
    lv_obj_set_y(ui_rssiLine3Panel, 9);
    lv_obj_set_align(ui_rssiLine3Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rssiLine3Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rssiLine3Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiLine3Panel, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiLine3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_internetLabel = lv_label_create(ui_networkContainer);
    lv_obj_set_width(ui_internetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_internetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_internetLabel, 14);
    lv_obj_set_y(ui_internetLabel, 1);
    lv_obj_set_align(ui_internetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_internetLabel, " ");
    lv_obj_set_style_text_color(ui_internetLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_internetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_internetLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backendContainer = lv_obj_create(ui_statusContainer);
    lv_obj_remove_style_all(ui_backendContainer);
    lv_obj_set_width(ui_backendContainer, 51);
    lv_obj_set_height(ui_backendContainer, 22);
    lv_obj_set_x(ui_backendContainer, -165);
    lv_obj_set_y(ui_backendContainer, 0);
    lv_obj_set_align(ui_backendContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_backendContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backendContainer, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backendContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backendBar = lv_bar_create(ui_backendContainer);
    lv_bar_set_range(ui_backendBar, 1, 100);
    lv_obj_set_width(ui_backendBar, 40);
    lv_obj_set_height(ui_backendBar, 9);
    lv_obj_set_align(ui_backendBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_backendBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backendBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_backendBar, lv_color_hex(0x77000F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backendBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_backendBar, lv_color_hex(0x003808), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_backendBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_hydrobrickContainer = lv_obj_create(ui_statusContainer);
    lv_obj_remove_style_all(ui_hydrobrickContainer);
    lv_obj_set_width(ui_hydrobrickContainer, 51);
    lv_obj_set_height(ui_hydrobrickContainer, 22);
    lv_obj_set_x(ui_hydrobrickContainer, -112);
    lv_obj_set_y(ui_hydrobrickContainer, 0);
    lv_obj_set_align(ui_hydrobrickContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hydrobrickContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hydrobrickContainer, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hydrobrickContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hydrobrickBar = lv_bar_create(ui_hydrobrickContainer);
    lv_bar_set_range(ui_hydrobrickBar, 1, 100);
    lv_obj_set_width(ui_hydrobrickBar, 40);
    lv_obj_set_height(ui_hydrobrickBar, 9);
    lv_obj_set_align(ui_hydrobrickBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_hydrobrickBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hydrobrickBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_hydrobrickBar, lv_color_hex(0x77000F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hydrobrickBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_hydrobrickBar, lv_color_hex(0x003808), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_hydrobrickBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_messageContainer = lv_obj_create(ui_statusContainer);
    lv_obj_remove_style_all(ui_messageContainer);
    lv_obj_set_width(ui_messageContainer, 248);
    lv_obj_set_height(ui_messageContainer, 22);
    lv_obj_set_x(ui_messageContainer, 40);
    lv_obj_set_y(ui_messageContainer, 0);
    lv_obj_set_align(ui_messageContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_messageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_messageContainer, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_messageContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_messageLabel = lv_label_create(ui_messageContainer);
    lv_obj_set_width(ui_messageLabel, 238);
    lv_obj_set_height(ui_messageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_messageLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_messageLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_messageLabel, "");
    lv_obj_set_style_text_font(ui_messageLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeContainer = lv_obj_create(ui_statusContainer);
    lv_obj_remove_style_all(ui_timeContainer);
    lv_obj_set_width(ui_timeContainer, 71);
    lv_obj_set_height(ui_timeContainer, 22);
    lv_obj_set_x(ui_timeContainer, 201);
    lv_obj_set_y(ui_timeContainer, 0);
    lv_obj_set_align(ui_timeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeContainer, lv_color_hex(0xE1E1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLabel = lv_label_create(ui_timeContainer);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "--:--");
    lv_obj_set_style_text_font(ui_timeLabel, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_voltPanel, 115);
    lv_obj_set_height(ui_voltPanel, 48);
    lv_obj_set_x(ui_voltPanel, 178);
    lv_obj_set_y(ui_voltPanel, -12);
    lv_obj_set_align(ui_voltPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_voltPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_voltPanel, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voltPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_voltPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_voltPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_voltPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_voltPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_voltLabel = lv_label_create(ui_voltPanel);
    lv_obj_set_width(ui_voltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltLabel, -10);
    lv_obj_set_y(ui_voltLabel, 11);
    lv_obj_set_align(ui_voltLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_voltLabel, "---");
    lv_obj_set_style_text_color(ui_voltLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltLabel, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltLabelDot = lv_label_create(ui_voltPanel);
    lv_obj_set_width(ui_voltLabelDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltLabelDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voltLabelDot, -19);
    lv_obj_set_y(ui_voltLabelDot, 8);
    lv_obj_set_align(ui_voltLabelDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voltLabelDot, ".");
    lv_obj_set_style_text_color(ui_voltLabelDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voltLabelDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltLabelDot, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitLabel1 = lv_label_create(ui_voltPanel);
    lv_obj_set_width(ui_unitLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unitLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unitLabel1, 45);
    lv_obj_set_y(ui_unitLabel1, -11);
    lv_obj_set_align(ui_unitLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unitLabel1, "V");
    lv_obj_set_style_text_color(ui_unitLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vhargeLabel = lv_label_create(ui_voltPanel);
    lv_obj_set_width(ui_vhargeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vhargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vhargeLabel, -5);
    lv_obj_set_y(ui_vhargeLabel, 0);
    lv_obj_set_align(ui_vhargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_vhargeLabel, "CHARGE");
    lv_obj_add_flag(ui_vhargeLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_vhargeLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vhargeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vhargeLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hbTempPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_hbTempPanel, 115);
    lv_obj_set_height(ui_hbTempPanel, 48);
    lv_obj_set_x(ui_hbTempPanel, 60);
    lv_obj_set_y(ui_hbTempPanel, -11);
    lv_obj_set_align(ui_hbTempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hbTempPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_hbTempPanel, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hbTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hbTempPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hbTempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hbTempPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_hbTempPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_hbTempLabel = lv_label_create(ui_hbTempPanel);
    lv_obj_set_width(ui_hbTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hbTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hbTempLabel, -23);
    lv_obj_set_y(ui_hbTempLabel, 11);
    lv_obj_set_align(ui_hbTempLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_hbTempLabel, "--");
    lv_obj_set_style_text_color(ui_hbTempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hbTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hbTempLabel, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hbTempLabelDot = lv_label_create(ui_hbTempPanel);
    lv_obj_set_width(ui_hbTempLabelDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hbTempLabelDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hbTempLabelDot, 16);
    lv_obj_set_y(ui_hbTempLabelDot, 8);
    lv_obj_set_align(ui_hbTempLabelDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hbTempLabelDot, ".");
    lv_obj_set_style_text_color(ui_hbTempLabelDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hbTempLabelDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hbTempLabelDot, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hbTempLabelSmall = lv_label_create(ui_hbTempPanel);
    lv_obj_set_width(ui_hbTempLabelSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hbTempLabelSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hbTempLabelSmall, -1);
    lv_obj_set_y(ui_hbTempLabelSmall, 8);
    lv_obj_set_align(ui_hbTempLabelSmall, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_hbTempLabelSmall, "-");
    lv_obj_set_style_text_color(ui_hbTempLabelSmall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hbTempLabelSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hbTempLabelSmall, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitLabel2 = lv_label_create(ui_hbTempPanel);
    lv_obj_set_width(ui_unitLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unitLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unitLabel2, 45);
    lv_obj_set_y(ui_unitLabel2, -11);
    lv_obj_set_align(ui_unitLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unitLabel2, "°C");
    lv_obj_set_style_text_color(ui_unitLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitLabel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_tempPanel, 233);
    lv_obj_set_height(ui_tempPanel, 100);
    lv_obj_set_x(ui_tempPanel, -119);
    lv_obj_set_y(ui_tempPanel, -89);
    lv_obj_set_align(ui_tempPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_tempPanel, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_tempPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_tempLabel = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, -60);
    lv_obj_set_y(ui_tempLabel, 0);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_tempLabel, "--");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabelDot = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempLabelDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabelDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabelDot, 39);
    lv_obj_set_y(ui_tempLabelDot, 2);
    lv_obj_set_align(ui_tempLabelDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabelDot, ".");
    lv_obj_set_style_text_color(ui_tempLabelDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabelDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabelDot, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabelSmall = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_tempLabelSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabelSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabelSmall, -19);
    lv_obj_set_y(ui_tempLabelSmall, -1);
    lv_obj_set_align(ui_tempLabelSmall, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_tempLabelSmall, "-");
    lv_obj_set_style_text_color(ui_tempLabelSmall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabelSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabelSmall, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_unitLabel = lv_label_create(ui_tempPanel);
    lv_obj_set_width(ui_unitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unitLabel, 70);
    lv_obj_set_y(ui_unitLabel, -30);
    lv_obj_set_align(ui_unitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_unitLabel, "°C");
    lv_obj_set_style_text_color(ui_unitLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_unitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_unitLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gravityPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_gravityPanel, 233);
    lv_obj_set_height(ui_gravityPanel, 100);
    lv_obj_set_x(ui_gravityPanel, 118);
    lv_obj_set_y(ui_gravityPanel, -89);
    lv_obj_set_align(ui_gravityPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gravityPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_gravityPanel, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gravityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_gravityPanel, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gravityPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gravityPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_gravityPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_gravityLabel = lv_label_create(ui_gravityPanel);
    lv_obj_set_width(ui_gravityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gravityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gravityLabel, -30);
    lv_obj_set_y(ui_gravityLabel, 1);
    lv_obj_set_align(ui_gravityLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_gravityLabel, " ---");
    lv_obj_set_style_text_color(ui_gravityLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gravityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gravityLabel, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gravityLabelDot = lv_label_create(ui_gravityPanel);
    lv_obj_set_width(ui_gravityLabelDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gravityLabelDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gravityLabelDot, -68);
    lv_obj_set_y(ui_gravityLabelDot, 2);
    lv_obj_set_align(ui_gravityLabelDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gravityLabelDot, ".");
    lv_obj_set_style_text_color(ui_gravityLabelDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gravityLabelDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gravityLabelDot, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gravityUnitLabel = lv_label_create(ui_gravityPanel);
    lv_obj_set_width(ui_gravityUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gravityUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gravityUnitLabel, 94);
    lv_obj_set_y(ui_gravityUnitLabel, -30);
    lv_obj_set_align(ui_gravityUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gravityUnitLabel, "SG");
    lv_obj_set_style_text_color(ui_gravityUnitLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gravityUnitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gravityUnitLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

}
