// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui_480x320

#ifndef _UI_480X320_UI_H
#define _UI_480X320_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_TitleContainer;
extern lv_obj_t * ui_titleLabel;
extern lv_obj_t * ui_weightPanel;
extern lv_obj_t * ui_weightLabel;
extern lv_obj_t * ui_weightLabelDot;
extern lv_obj_t * ui_weightLabelSmall;
extern lv_obj_t * ui_KgLabel;
extern lv_obj_t * ui_M1Panel;
extern lv_obj_t * ui_weightM1Label;
extern lv_obj_t * ui_weightLabelDot11;
extern lv_obj_t * ui_M1Label;
extern lv_obj_t * ui_M2Panel;
extern lv_obj_t * ui_confirmContainer;
extern lv_obj_t * ui_confirmPanel;
extern lv_obj_t * ui_confirmTextLabel;
void ui_event_OKButton(lv_event_t * e);
extern lv_obj_t * ui_OKButton;
extern lv_obj_t * ui_OKLabel;
extern lv_obj_t * ui_CANCELButton;
extern lv_obj_t * ui_CANCELLabel;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_weight100Font);
LV_FONT_DECLARE(ui_font_weight25Font);
LV_FONT_DECLARE(ui_font_weight50Font);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
