// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_logScreen_screen_init(void)
{
    ui_logScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_logScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_logScreen);
    lv_obj_set_width(ui_Panel1, 302);
    lv_obj_set_height(ui_Panel1, 191);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 15);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_TextArea1, 288);
    lv_obj_set_height(ui_TextArea1, 171);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1,
                         "s.dgknm.asfgdd\nfGdf\ng\ndfg\nadfg\na\ndfg\ndf\ng\nadf\nga\ndfg\nadf\ng\nafd\nga\nfdg\na\nfdgagjhnfhjsfh\nj\ng\nadf\nghadf\njag\ndh\ndfg\nasfdgh\nsadfg");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



}
