// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ui_480x320

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_TitleContainer);
    lv_obj_set_width(ui_TitleContainer, 480);
    lv_obj_set_height(ui_TitleContainer, 22);
    lv_obj_set_x(ui_TitleContainer, -1);
    lv_obj_set_y(ui_TitleContainer, -149);
    lv_obj_set_align(ui_TitleContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TitleContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TitleContainer, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitleContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleLabel = lv_label_create(ui_TitleContainer);
    lv_obj_set_align(ui_titleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titleLabel, "BOOKES BRICK");
    lv_obj_set_style_text_color(ui_titleLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titleLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_weightPanel, 215);
    lv_obj_set_height(ui_weightPanel, 100);
    lv_obj_set_x(ui_weightPanel, -126);
    lv_obj_set_y(ui_weightPanel, -82);
    lv_obj_set_align(ui_weightPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_weightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weightPanel, lv_color_hex(0x8B91FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weightPanel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_weightPanel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_weightLabel = lv_label_create(ui_weightPanel);
    lv_obj_set_width(ui_weightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabel, -60);
    lv_obj_set_y(ui_weightLabel, 0);
    lv_obj_set_align(ui_weightLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_weightLabel, "--");
    lv_obj_set_style_text_color(ui_weightLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLabel, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLabelDot = lv_label_create(ui_weightPanel);
    lv_obj_set_width(ui_weightLabelDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabelDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabelDot, 39);
    lv_obj_set_y(ui_weightLabelDot, 2);
    lv_obj_set_align(ui_weightLabelDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weightLabelDot, ".");
    lv_obj_set_style_text_color(ui_weightLabelDot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLabelDot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLabelDot, &ui_font_weight100Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLabelSmall = lv_label_create(ui_weightPanel);
    lv_obj_set_width(ui_weightLabelSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabelSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabelSmall, -19);
    lv_obj_set_y(ui_weightLabelSmall, -1);
    lv_obj_set_align(ui_weightLabelSmall, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_weightLabelSmall, "-");
    lv_obj_set_style_text_color(ui_weightLabelSmall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLabelSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLabelSmall, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KgLabel = lv_label_create(ui_weightPanel);
    lv_obj_set_width(ui_KgLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KgLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KgLabel, 70);
    lv_obj_set_y(ui_KgLabel, -30);
    lv_obj_set_align(ui_KgLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KgLabel, "°C");
    lv_obj_set_style_text_color(ui_KgLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_KgLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_KgLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_M1Panel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_M1Panel, 90);
    lv_obj_set_height(ui_M1Panel, 48);
    lv_obj_set_x(ui_M1Panel, 186);
    lv_obj_set_y(ui_M1Panel, -106);
    lv_obj_set_align(ui_M1Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_M1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_M1Panel, lv_color_hex(0x8B91FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_M1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_M1Panel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_M1Panel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_weightM1Label = lv_label_create(ui_M1Panel);
    lv_obj_set_width(ui_weightM1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightM1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightM1Label, -19);
    lv_obj_set_y(ui_weightM1Label, 8);
    lv_obj_set_align(ui_weightM1Label, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_weightM1Label, "--");
    lv_obj_set_style_text_color(ui_weightM1Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightM1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightM1Label, &ui_font_weight50Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weightLabelDot11 = lv_label_create(ui_M1Panel);
    lv_obj_set_width(ui_weightLabelDot11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weightLabelDot11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weightLabelDot11, 20);
    lv_obj_set_y(ui_weightLabelDot11, 8);
    lv_obj_set_align(ui_weightLabelDot11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weightLabelDot11, ".");
    lv_obj_set_style_text_color(ui_weightLabelDot11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weightLabelDot11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weightLabelDot11, &ui_font_weight25Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_M1Label = lv_label_create(ui_M1Panel);
    lv_obj_set_width(ui_M1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_M1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_M1Label, 27);
    lv_obj_set_y(ui_M1Label, -11);
    lv_obj_set_align(ui_M1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_M1Label, "SET");
    lv_obj_set_style_text_color(ui_M1Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_M1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_M2Panel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_M2Panel, 90);
    lv_obj_set_height(ui_M2Panel, 48);
    lv_obj_set_x(ui_M2Panel, 186);
    lv_obj_set_y(ui_M2Panel, -54);
    lv_obj_set_align(ui_M2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_M2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_M2Panel, lv_color_hex(0x8B91FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_M2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_M2Panel, lv_color_hex(0xCCCEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_M2Panel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_confirmContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_confirmContainer);
    lv_obj_set_width(ui_confirmContainer, 320);
    lv_obj_set_height(ui_confirmContainer, 240);
    lv_obj_set_align(ui_confirmContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_confirmContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_confirmContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmPanel = lv_obj_create(ui_confirmContainer);
    lv_obj_set_width(ui_confirmPanel, 260);
    lv_obj_set_height(ui_confirmPanel, 131);
    lv_obj_set_align(ui_confirmPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_confirmPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confirmPanel, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confirmPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confirmPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confirmPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmTextLabel = lv_label_create(ui_confirmPanel);
    lv_obj_set_width(ui_confirmTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confirmTextLabel, -4);
    lv_obj_set_y(ui_confirmTextLabel, -42);
    lv_obj_set_align(ui_confirmTextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmTextLabel, "SET WEIGHT TO ZERO ?");

    ui_OKButton = lv_btn_create(ui_confirmPanel);
    lv_obj_set_width(ui_OKButton, 100);
    lv_obj_set_height(ui_OKButton, 50);
    lv_obj_set_x(ui_OKButton, -58);
    lv_obj_set_y(ui_OKButton, 15);
    lv_obj_set_align(ui_OKButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OKButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OKButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OKButton, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OKButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OKLabel = lv_label_create(ui_OKButton);
    lv_obj_set_align(ui_OKLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OKLabel, "OK");

    ui_CANCELButton = lv_btn_create(ui_confirmPanel);
    lv_obj_set_width(ui_CANCELButton, 100);
    lv_obj_set_height(ui_CANCELButton, 50);
    lv_obj_set_x(ui_CANCELButton, 56);
    lv_obj_set_y(ui_CANCELButton, 15);
    lv_obj_set_align(ui_CANCELButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CANCELButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CANCELButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CANCELButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CANCELButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CANCELLabel = lv_label_create(ui_CANCELButton);
    lv_obj_set_align(ui_CANCELLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CANCELLabel, "CANCEL");

    lv_obj_add_event_cb(ui_OKButton, ui_event_OKButton, LV_EVENT_ALL, NULL);

}
